"""
Unit tests for app/validator/sql_validator.py

Test authorship note
--------------------
These tests were designed by the developer — NOT generated by an LLM.
They define the expected behavior of the validator and serve as the
specification that any implementation (including LLM-assisted code) must satisfy.

LLM failure case documented here
---------------------------------
When the LLM initially implemented extract_referenced_tables it produced:

    pattern = r'\\bFROM\\s+([a-zA-Z_][a-zA-Z0-9_]*)'

This regex only captures the *first* identifier after FROM.
It fails for comma-separated multi-table queries such as:

    SELECT * FROM users, orders

test_extract_comma_separated_tables caught the failure.
The implementation was refined to split the FROM clause on commas
and extract the first token from each segment.
"""

import os
import sqlite3
import tempfile
import unittest

from app.validator.sql_validator import (
    check_no_injection_patterns,
    check_query_type,
    check_tables_exist,
    extract_referenced_tables,
    get_db_tables,
    validate_query,
)


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #

def _make_db(tables):
    """
    Create a temporary SQLite database with the given tables and return its path.

    Args:
        tables (list[str]): Table names to create (schema doesn't matter for
                            validator tests — existence is all that counts).

    Returns:
        str: Path to the temp database file.
    """
    fd, path = tempfile.mkstemp(suffix=".db")
    os.close(fd)
    conn = sqlite3.connect(path)
    for table in tables:
        conn.execute(
            f"CREATE TABLE {table} (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT)"
        )
    conn.commit()
    conn.close()
    return path


# --------------------------------------------------------------------------- #
# check_query_type
# --------------------------------------------------------------------------- #

class TestCheckQueryType(unittest.TestCase):

    def test_select_is_allowed(self):
        valid, error = check_query_type("SELECT * FROM users")
        self.assertTrue(valid)
        self.assertIsNone(error)

    def test_select_lowercase_is_allowed(self):
        valid, error = check_query_type("select id from users")
        self.assertTrue(valid)
        self.assertIsNone(error)

    def test_insert_is_blocked(self):
        valid, error = check_query_type("INSERT INTO users VALUES (1, 'a')")
        self.assertFalse(valid)
        self.assertIn("INSERT", error)

    def test_update_is_blocked(self):
        valid, error = check_query_type("UPDATE users SET name='x' WHERE id=1")
        self.assertFalse(valid)

    def test_delete_is_blocked(self):
        valid, error = check_query_type("DELETE FROM users WHERE id=1")
        self.assertFalse(valid)

    def test_drop_is_blocked(self):
        valid, error = check_query_type("DROP TABLE users")
        self.assertFalse(valid)

    def test_create_is_blocked(self):
        valid, error = check_query_type("CREATE TABLE foo (id INTEGER)")
        self.assertFalse(valid)

    def test_empty_query_is_blocked(self):
        valid, error = check_query_type("")
        self.assertFalse(valid)

    def test_whitespace_only_is_blocked(self):
        valid, error = check_query_type("   ")
        self.assertFalse(valid)


# --------------------------------------------------------------------------- #
# check_no_injection_patterns
# --------------------------------------------------------------------------- #

class TestCheckNoInjectionPatterns(unittest.TestCase):

    def test_clean_query_passes(self):
        valid, error = check_no_injection_patterns("SELECT id, name FROM users")
        self.assertTrue(valid)
        self.assertIsNone(error)

    def test_line_comment_is_blocked(self):
        valid, error = check_no_injection_patterns("SELECT * FROM users -- comment")
        self.assertFalse(valid)
        self.assertIn("--", error)

    def test_block_comment_open_is_blocked(self):
        valid, error = check_no_injection_patterns("SELECT /* trick */ * FROM users")
        self.assertFalse(valid)

    def test_block_comment_close_is_blocked(self):
        valid, error = check_no_injection_patterns("SELECT * FROM users */")
        self.assertFalse(valid)

    def test_semicolon_is_blocked(self):
        # Prevents multi-statement injection: SELECT 1; DROP TABLE users
        valid, error = check_no_injection_patterns("SELECT * FROM users; DROP TABLE users")
        self.assertFalse(valid)
        self.assertIn(";", error)

    def test_exec_keyword_is_blocked(self):
        valid, error = check_no_injection_patterns("SELECT EXEC('xp_cmdshell')")
        self.assertFalse(valid)

    def test_xp_prefix_is_blocked(self):
        valid, error = check_no_injection_patterns("SELECT xp_cmdshell FROM users")
        self.assertFalse(valid)

    def test_where_clause_with_operators_passes(self):
        # Normal WHERE clauses must not be blocked
        valid, error = check_no_injection_patterns(
            "SELECT * FROM users WHERE age > 18 AND name = 'Alice'"
        )
        self.assertTrue(valid)


# --------------------------------------------------------------------------- #
# extract_referenced_tables
# --------------------------------------------------------------------------- #

class TestExtractReferencedTables(unittest.TestCase):

    def test_single_table(self):
        tables = extract_referenced_tables("SELECT * FROM users")
        self.assertEqual(set(tables), {"users"})

    def test_join_table(self):
        tables = extract_referenced_tables(
            "SELECT * FROM users JOIN orders ON users.id = orders.user_id"
        )
        self.assertEqual(set(tables), {"users", "orders"})

    # --- LLM FAILURE CASE ---
    # The LLM's first implementation used a simple FROM regex that only
    # captured the first table name after FROM.  This test caught the bug.
    def test_extract_comma_separated_tables(self):
        tables = extract_referenced_tables("SELECT * FROM users, orders")
        self.assertEqual(
            set(tables), {"users", "orders"},
            "Comma-separated FROM tables must all be extracted"
        )

    def test_three_comma_separated_tables(self):
        tables = extract_referenced_tables("SELECT * FROM users, orders, products")
        self.assertEqual(set(tables), {"users", "orders", "products"})

    def test_multiple_joins(self):
        sql = (
            "SELECT * FROM orders "
            "JOIN users ON orders.user_id = users.id "
            "JOIN products ON orders.product_id = products.id"
        )
        tables = extract_referenced_tables(sql)
        self.assertEqual(set(tables), {"orders", "users", "products"})

    def test_table_alias_ignored(self):
        # Alias 'u' must not appear in results — 'users' should
        tables = extract_referenced_tables("SELECT u.name FROM users u")
        self.assertIn("users", tables)
        self.assertNotIn("u", tables)

    def test_table_as_alias_ignored(self):
        tables = extract_referenced_tables("SELECT u.name FROM users AS u")
        self.assertIn("users", tables)
        self.assertNotIn("u", tables)

    def test_no_from_clause_returns_empty(self):
        tables = extract_referenced_tables("SELECT 1 + 1")
        self.assertEqual(tables, [])

    def test_case_insensitive_from(self):
        tables = extract_referenced_tables("select * from users")
        self.assertEqual(set(tables), {"users"})

    def test_names_are_lowercased(self):
        tables = extract_referenced_tables("SELECT * FROM Users")
        self.assertIn("users", tables)


# --------------------------------------------------------------------------- #
# check_tables_exist
# --------------------------------------------------------------------------- #

class TestCheckTablesExist(unittest.TestCase):

    def setUp(self):
        self.db_path = _make_db(["users", "orders"])

    def tearDown(self):
        os.unlink(self.db_path)

    def test_existing_table_passes(self):
        valid, error = check_tables_exist(["users"], self.db_path)
        self.assertTrue(valid)
        self.assertIsNone(error)

    def test_multiple_existing_tables_pass(self):
        valid, error = check_tables_exist(["users", "orders"], self.db_path)
        self.assertTrue(valid)

    def test_nonexistent_table_is_blocked(self):
        valid, error = check_tables_exist(["ghosts"], self.db_path)
        self.assertFalse(valid)
        self.assertIn("ghosts", error)

    def test_mix_of_existing_and_missing_is_blocked(self):
        valid, error = check_tables_exist(["users", "ghosts"], self.db_path)
        self.assertFalse(valid)
        self.assertIn("ghosts", error)

    def test_empty_table_list_passes(self):
        # No tables referenced (e.g. SELECT 1+1) — nothing to check
        valid, error = check_tables_exist([], self.db_path)
        self.assertTrue(valid)

    def test_table_name_case_insensitive(self):
        valid, error = check_tables_exist(["USERS"], self.db_path)
        self.assertTrue(valid)


# --------------------------------------------------------------------------- #
# validate_query  (end-to-end)
# --------------------------------------------------------------------------- #

class TestValidateQuery(unittest.TestCase):

    def setUp(self):
        self.db_path = _make_db(["users", "orders"])

    def tearDown(self):
        os.unlink(self.db_path)

    def test_valid_select_passes(self):
        result = validate_query("SELECT * FROM users", self.db_path)
        self.assertTrue(result["valid"])
        self.assertIsNone(result["error"])

    def test_valid_join_passes(self):
        result = validate_query(
            "SELECT * FROM users JOIN orders ON users.id = orders.user_id",
            self.db_path,
        )
        self.assertTrue(result["valid"])

    def test_nonexistent_table_fails(self):
        result = validate_query("SELECT * FROM invoices", self.db_path)
        self.assertFalse(result["valid"])
        self.assertIn("invoices", result["error"])

    def test_insert_fails(self):
        result = validate_query("INSERT INTO users VALUES (1)", self.db_path)
        self.assertFalse(result["valid"])

    def test_semicolon_injection_fails(self):
        result = validate_query(
            "SELECT * FROM users; DROP TABLE users", self.db_path
        )
        self.assertFalse(result["valid"])

    def test_comment_injection_fails(self):
        result = validate_query(
            "SELECT * FROM users -- bypass", self.db_path
        )
        self.assertFalse(result["valid"])

    def test_result_has_required_keys(self):
        result = validate_query("SELECT 1", self.db_path)
        self.assertIn("valid", result)
        self.assertIn("error", result)


if __name__ == "__main__":
    unittest.main()
