"""
Query Service
=============
Provides two entry points for running queries against the database.

Step 1 — Direct SQL path (raw input from the user):
    run_query(sql, db_path)

Step 2 — LLM-assisted path (SQL generated by the LLM Adapter):
    run_llm_query(question, db_path, generate_fn)

Both paths pass through the *same* validator before any SQL touches
the database.  The LLM Adapter never executes SQL directly.
"""

from app.validator.sql_validator import validate_query
from app.db.database import fetch_all_records
from app.utils.logger import log_error, log_info


def run_sql_query(sql_query, db_path):
    """
    Execute a user-supplied SQL query after validation.

    Args:
        sql_query (str): Raw SQL query entered by the user.
        db_path (str): Path to the SQLite database.

    Returns:
        dict: A dictionary containing the query result or error details.
            {
                "success": bool,
                "columns": list[str],
                "rows": list[tuple],
                "error": str | None
            }
    """
    validation_result = validate_query(sql_query, db_path)
    if not validation["valid"]:
        return {
            "success": False,
            "columns": [],
            "rows": [],
            "error": validation["error"],
        }

    try:
        columns, rows = fetch_all(db_path, sql)
        log_info(f"Query returned {len(rows)} row(s).")
        return {
            "success": True,
            "columns": columns,
            "rows": rows,
            "error": None,
        }
    except Exception as e:
        log_error(str(e))
        return {
            "success": False,
            "columns": [],
            "rows": [],
            "error": f"Execution error: {str(e)}",
        }


def run_llm_query(question, db_path, generate_fn):
    """
    Generate SQL query from a natural language question using the LLM Adapter,
    validate it, and execute it.

    Args:
        question (str): Natural language question from the user.
        db_path (str): Path to the SQLite database.
        generate_sql_fn (callable): Function with signature:
                                    generate_sql_fn(question, db_path) -> str
                                    (provided by llm_adapter.adapter)

    Returns:
        dict: Same shape as run_sql_query, with an additional "generated_sql" key
              to show the user the generated SQL query.
    """
    try:
        generated_sql = generate_sql_fn(question, db_path)
    except Exception as e:
        log_error(str(e))
        return {
            "success": False,
            "columns": [],
            "rows": [],
            "generated_sql": None,
            "error": f"LLM error: {str(e)}",
        }

    query_result = run_sql_query(generated_sql, db_path)
    query_result["generated_sql"] = generated_sql
    return query_result
