"""
Query Service
=============
Provides two entry points for running queries against the database.

Step 1 — Direct SQL path (raw input from the user):
    run_query(sql, db_path)

Step 2 — LLM-assisted path (SQL generated by the LLM Adapter):
    run_llm_query(question, db_path, generate_fn)

Both paths pass through the *same* validator before any SQL touches
the database.  The LLM Adapter never executes SQL directly.
"""

from app.validator.sql_validator import validate_query
from app.db.database import fetch_all
from app.utils.logger import log_error, log_info


def run_query(sql, db_path):
    """
    Step 1: Validate a user-supplied SQL query, then execute it.

    Args:
        sql (str): Raw SQL string entered by the user.
        db_path (str): Path to the SQLite database.

    Returns:
        dict: {
            "success": bool,
            "columns": list[str],
            "rows": list[tuple],
            "error": str | None
        }
    """
    validation = validate_query(sql, db_path)
    if not validation["valid"]:
        return {
            "success": False,
            "columns": [],
            "rows": [],
            "error": validation["error"],
        }

    try:
        columns, rows = fetch_all(db_path, sql)
        log_info(f"Query returned {len(rows)} row(s).")
        return {
            "success": True,
            "columns": columns,
            "rows": rows,
            "error": None,
        }
    except Exception as e:
        log_error(str(e))
        return {
            "success": False,
            "columns": [],
            "rows": [],
            "error": f"Execution error: {str(e)}",
        }


def run_llm_query(question, db_path, generate_fn):
    """
    Step 2: Ask the LLM Adapter to generate SQL from a natural language
    question, validate it, then execute it.

    The generate_fn parameter accepts the schema description and question
    and returns a SQL string — it never touches the database.

    Args:
        question (str): Natural language question from the user.
        db_path (str): Path to the SQLite database.
        generate_fn (callable): Function with signature
                                generate_fn(question, db_path) -> str
                                (provided by llm_adapter.adapter)

    Returns:
        dict: Same shape as run_query — adds "generated_sql" key so the
              caller can show the user what SQL was produced.
    """
    try:
        sql = generate_fn(question, db_path)
    except Exception as e:
        log_error(str(e))
        return {
            "success": False,
            "columns": [],
            "rows": [],
            "generated_sql": None,
            "error": f"LLM error: {str(e)}",
        }

    result = run_query(sql, db_path)
    result["generated_sql"] = sql
    return result
